### ISSUE TITLE
Field Names ARIstoteles vs. libARI.dylib

### ISSUE THREAD

**Issue by sterzy** [seemoo-lab/aristoteles#7]
Field names in the dissector differ from log strings and function signatures in `libARI.dylib`. This may be relevant and should probably be documented. Examples:

| ARIstoteles | `libARI.dylib`                                 |
|-------------|------------------------------------------------|
| Group       | gid or just g                                  |
| Type id     | mid or just m                                  |
| ID (TLVs)   | tid                                            |
| Transaction | Either `ctx` (context) or `trx` (transaction). |

Sample log strings:

```
(%s:%d) trying to pack gid(%d) mid(0x%03x) tid(%d) with sz(%zu) > max size(%zu)
(%s:%d) trying to pack gid(%d) mid(0x%03x) tid(%d) with sz(%zu) not multiple of element sz(%zu)
(%s:%d) UNKNOWN tlv with g(%d) m(0x%03x) tid(%d), ignored
(%s:%d) canceling ctx 0x%x gmid 0x%x %s
(%s:%d) Client (0x%x) cancelTrx(0x%x) done
```

Symbols for functions:

| Symbol (frida)              | Function signature                                |
|-----------------------------|---------------------------------------------------|
| `_ZN6AriMsg9GetBufGidEPKhm` | `AriMsg::GetBufGid(uint32_t * buf, uint64_t len)` |
| `_ZN6AriMsg9GetBufMidEPKhm` | `AriMsg::GetBufMid(uint32_t * buf, uint64_t len)` |
| `_ZN6AriMsg9GetBufCtxEPKhm` | `AriMsg::GetBufCtx(uint32_t * buf, uint64_t len)` |

**Comment by saibotk** [comment]
![image](https://user-images.githubusercontent.com/10776964/143785477-96b94c98-7f5c-4e25-8663-6a60638e3ee4.png)

I decided that it would be better for those identifiers to be shown in the dissector, rather than documenting them in the README or elsewhere.
